[theme]
base="light"
primaryColor = "#818d3f"           
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#abbf5340"
textColor = "#1C1C1C"
font = "sans-serif"
headingFont = "serif"
linkColor = "#4f5926"
dataframeHeaderBackgroundColor = "#f4f8e2"

[theme.sidebar]
borderColor = "#212510"
primaryColor = "#818d3f"
backgroundColor = "#f4f8e2"
secondaryBackgroundColor="#f4f8e2"
showWidgetBorder=true
